biolab/orange3-prototypes

orangecontrib/prototypes/widgets/icons/LinearProjection.svg, orangecontrib/prototypes/widgets/owlda.py, orangecontrib/prototypes/widgets/owlinearprojection.py
Transfered from pull request
https://github.com/biolab/orange3/pull/665
=> LinearProjection: Add optimizations

orangecontrib/prototypes/widgets/icons/DBSCAN.svg, orangecontrib/prototypes/widgets/owdbscan.py
Copied from pull request
https://github.com/biolab/orange3/pull/605
=> DBSCAN: Create widget

orangecontrib/prototypes/widgets/icons/GoogleSheets.svg, orangecontrib/prototypes/widgets/owgooglesheets.py, setup.py
This replaces https://github.com/biolab/orange3/pull/678 temporarily.
=> OWGoogleSheets: new data source

orangecontrib/prototypes/widgets/icons/Hub.svg, orangecontrib/prototypes/widgets/owhub.py
As advertised in https://docs.google.com/document/d/1ulaWDXqB6RFPOOFvaSc8cnOs0yLwVYfMYrKov4ueUi0/edit?usp=sharing
=> WIP Hub widget: initial commit

orangecontrib/prototypes/widgets/owlineplot.py
Removed hover lines, which made annotations and commit obsolete.
=> LinePlot: Remove hover lines for speed-up

orangecontrib/prototypes/widgets/owfreeviz.py
This is a partial port of FreeViz functionality from Linear Projections in Orange3.
=> owfreeviz: Add a new FreeViz widget

orangecontrib/prototypes/projection/freeviz.py, orangecontrib/prototypes/widgets/owfreeviz.py
* Allow user to select color/shape/size/label variable
* Add plot jittering
* Add plot point tool tips
* Optionally display class variable density image
* Add (port from orange2) support for continuous class variables
* Change step size scaling (compatibility with Orange 2)
=> Extend FreeViz widget

orangecontrib/prototypes/widgets/owlinearprojection.py
Due to a change in the base OWWidget
=> owlinearprojection: Fix graph save

orangecontrib/prototypes/widgets/icons/Neighbours.svg, orangecontrib/prototypes/widgets/owneighbours.py
The widget finds k most similar instances from collection, according to the seed instances.
=> OWNeighbours: Add new widget

orangecontrib/prototypes/widgets/owneighbours.py, orangecontrib/prototypes/widgets/tests/test_owneighbours.py
Add distance combo box, rename seed to reference, enable excluding reference.
=> OWNeighbours: Widget upgrade

orangecontrib/prototypes/widgets/icons/Unique.svg, orangecontrib/prototypes/widgets/owlda.py, orangecontrib/prototypes/widgets/owunique.py
Widget that filters data instances as determined unique on a chosen key.
Blocked by https://github.com/biolab/orange3/pull/1843
=> Unique widget - filter unique instances

orangecontrib/prototypes/widgets/owneighbours.py
Data attributes from the incoming data table are added to the output table.
=> [FIX] OWNeighbours: add data attributes to the output table

orangecontrib/prototypes/widgets/icons/Contingency.svg, orangecontrib/prototypes/widgets/owcontingency.py
Prototype implementation of a Contingency Table widget.
Missing documentation and tests.
=> owcontingency: Add a prototype Contingency Table widget

orangecontrib/prototypes/widgets/owcontingency.py
Fix mixed up column/row variables.
=> owcontingency: Fix column/row variable.

orangecontrib/prototypes/widgets/owscattermap.py
Widget was moved to prototypes before these fixes were merged.
=> Scattermap: Fixes from orange3#1984

orangecontrib/prototypes/widgets/icons/Correlations.svg, orangecontrib/prototypes/widgets/icons/DataSets.svg
Correlations and Data Sets icons redesign.
=> Icon redesign

orangecontrib/prototypes/widgets/owfreeviz.py, orangecontrib/prototypes/widgets/tests/test_owfreeviz.py
Some changes should be made before it is moved to core Orange.
- control area should be similar to ScatterPlot
- output annotated data
Do not merge before
https://github.com/biolab/orange3/pull/2174 and 
https://github.com/biolab/orange3/pull/2173 are merged.
=> OWFreeViz: Updates

orangecontrib/prototypes/widgets/owdatasets.py
1) Rename headers:
Name -> Title
Class -> Target
2) Handle plural in control area info box
3) Change the description box.
- Includes an itemized list of references
- TODO: `See Also:` section
=> Data Sets: Updates

orangecontrib/prototypes/widgets/owdatasets.py
- Detect urls and convert to html links
- Add "See Also" section (when available)
- Add "Source" link (when available)
- Style changes
=> [WIP] owdatasets: Linkify urls, add See Also, update style

orangecontrib/prototypes/widgets/ow1ka.py
Fixes https://github.com/biolab/orange3-prototypes/issues/92
=> OW1Ka: fix crash if link contains no survey responses

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, orangecontrib/prototypes/widgets/owfreeviz.py
FreeViz has not been working since new MDS was merged.
Also GitHub templates added.
=> [FIX] FreeViz: work again

orangecontrib/prototypes/widgets/owfreeviz.py
Freeviz will not work when https://github.com/biolab/orange3/pull/2445 is merged.
Just copied code from old Linear Projection to Prototypes's FreeViz.
=> [FIX] FreeViz: work when Linear Projection is merged

orangecontrib/prototypes/stack.py, orangecontrib/prototypes/widgets/owstack.py
Adds a new widget for stacking.
To be expanded with:
- make aggregator input optional and use a default when not supplied?
- error messages (incorrect mixing of classification/regression learners e.g. lin reg and log reg, ...)
- gui element to set parameter k (for cv) ?
- tests & documentation :)
=> Stacking widget

orangecontrib/prototypes/widgets/owlineplot.py
Widget needs renovation.
First two things to do: use ```AnyQt``` and **new signals**.
=> [FIX] Line Plot: PyQt4 -> AnyQt & new signals

orangecontrib/prototypes/widgets/owfeaturestatistics.py
@kernc I've just noticed that an icon for the widget exists in the `icons` folder, so I added a reference to that.
=> OWFeatureStatistics: Specify icon

orangecontrib/prototypes/widgets/owselectsubset.py, orangecontrib/prototypes/widgets/tests/test_owselectsubset.py
=> Select subset widget

orangecontrib/prototypes/widgets/owcorrelations.py
Widget not yet updated to latest changes.
- new inputs and outputs
- size hint
- Report button removed since it is now in status bar
=> Updated Correlations widget

orangecontrib/prototypes/widgets/owfeaturestatistics.py
Fixes #125
#125 @ajdapretnar 
Remove "Send" button and remove row selection.
=> OWFeatureStatistics: Remove selection and send button

orangecontrib/prototypes/widgets/owlineplot.py
https://github.com/biolab/orange3-prototypes/issues/128
=> owlineplot: display graph if there is no discrete variable

orangecontrib/prototypes/widgets/owlineplot.py, orangecontrib/prototypes/widgets/tests/test_owlineplot.py
=> OWLinePlot: Data selection and some fixups

orangecontrib/prototypes/widgets/owlineplot.py, orangecontrib/prototypes/widgets/tests/test_owlineplot.py
=> OWLinePlot: Add Data Subset input signal

orangecontrib/prototypes/widgets/owlineplot.py
=> OWLinePlot: Fix bug made in commit ff4917c

orangecontrib/prototypes/widgets/owlineplot.py, orangecontrib/prototypes/widgets/tests/test_owlineplot.py
=> OWLinePlot: Line instead of rect when selecting lines, refactor, speedup

orangecontrib/prototypes/widgets/owexplpred.py
Widget that computes attribute contributions using shapely value, by employing an approximation algorithm. 
Added rudimentary version of the proposed widget.
=> Widget ExplainPredictions

orangecontrib/prototypes/widgets/owlineplot.py, orangecontrib/prototypes/widgets/tests/test_owlineplot.py
Visualization of selected data in LinePlot widget was very confusing and not really obvious to the user.
Add 'Range (min-max) with mean' to display options.
Resize widget.
Add legend.
=> OWLinePlot: Widget updates

doc/widgets/stacking.rst, orangecontrib/prototypes/stack.py, orangecontrib/prototypes/tests/test_stack.py, orangecontrib/prototypes/widgets/owstack.py
Fixes #153 
Add StackingFitter to choose the correct default aggregator.
=> [FIX] OWStack: Add default aggregator

orangecontrib/prototypes/widgets/owlineplot.py, orangecontrib/prototypes/widgets/tests/test_owlineplot.py
Needs merging of https://github.com/biolab/orange3/pull/3329
=> [ENH] Line Plot: Speed up and enhancements

.gitignore
Ignore built doc files in git.
=> Ignore build docs in git

orangecontrib/prototypes/widgets/owcsvimport.py, orangecontrib/prototypes/widgets/tests/test_owcsvimport.py
=> [FIX] CSV Import: Fix N/A parsing for text columns

orangecontrib/prototypes/widgets/owdbscan.py, orangecontrib/prototypes/widgets/tests/test_owdbscan.py
- The widget does not work since clustering in Orange has changed.
- The widget does not match with other clustering methods
- The widget does not match with updated widget design in Orange
- No unit-tests
All issues are addressed in this PR.
=> DBSCAN: widget fixed and updated

orangecontrib/prototypes/widgets/owdbscan.py, orangecontrib/prototypes/widgets/tests/test_owdbscan.py
- DBSCAN Core changed to DiscretVariable
- Epsilon spin changed step to 0.01
- Added test for sparse data
=> OWDBSCAN: Additional fixed and tests

orangecontrib/prototypes/tests/__init__.py, setup.py
Running `python setup.py test` executed some other `orangecontrib` tests.
Added a test suite.
=> Define test suite

orangecontrib/prototypes/widgets/icons/ExplainModel.svg, orangecontrib/prototypes/widgets/owexplainmodel.py, orangecontrib/prototypes/widgets/tests/test_owexplainmodel.py
=> [ENH] Explain model: New widget

orangecontrib/prototypes/widgets/icons/ExplainPred.svg, orangecontrib/prototypes/widgets/owexplainpred.py, orangecontrib/prototypes/widgets/tests/test_owexplainpred.py
=> [ENH] Explain Predictions: New widget

orangecontrib/prototypes/widgets/owexplainmodel.py
Explain Model widget has plot of fixed size and too much empty space when enlarged.
Adjust plot width to widget size.
=> Explain Model: Resizable plot 2.

orangecontrib/prototypes/widgets/owexplainmodel.py, orangecontrib/prototypes/widgets/tests/test_owexplainmodel.py
Enable showing/hiding the legend.
Add a check box to show legend.
=> Explain Model: Show/hide legend

orangecontrib/prototypes/explanation/explainer.py
The explainer for trees (e.g. random forest) is fast in most cases but in cases when model is complex it is still quite slow. 
Improved speed for the tree explainer:
- explain only the sample at most 1000 cases (before 10000)
- use background data for perturbation (before it wasn't using reference data but took the distribution from the tree - it is slower for large trees)
=> Explainer: speedup for complex trees

orangecontrib/prototypes/widgets/owexplainpred.py
Round values displayed in tooltips to 3 decimals.
=> Explain Prediction: Round tooltip values

README.pypi, setup.py
Missing PyPi description
Added simple description for PyPI.
=> PyPI description

orangecontrib/prototypes/widgets/owdfdisplay.py
A prototype lightweight table display widget to display Table, DataFrame, ndarray, or sparse matrices.
=> [ENH] Data Display Widget

orangecontrib/prototypes/explanation/explainer.py, orangecontrib/prototypes/explanation/tests/test_explainer.py, setup.py
SHAP recently released a new version with significant changes. Some functions we are using are just removed or moved.
Updating explainer to newer SHAP version and fixing its version such that it cannot break compatibility in the future. Each new version will be tested first and the used.
=> Update explainer to newer shap versions

orangecontrib/prototypes/widgets/owcreatetable.py, orangecontrib/prototypes/widgets/tests/test_owcreatetable.py
Implements #214
- Make widget remembers the data for the domain in the context
- Increase the initial table size
- Allow mixed numbers and string in the same column
- Support for the time variable
- Fix bug: data removed when line edit opened
- Tests
- Code cleanup
- Documentation
=> Improvement of create table widget

setup.py
=> Upgrade shap version to 0.37

.coveragerc, .github/workflows/test.yml, .gitignore, MANIFEST.in, orangecontrib/prototypes/tests/__init__.py, orangecontrib/prototypes/widgets/owcreatetable.py, orangecontrib/prototypes/widgets/tests/test_owgrep.py, pyproject.toml, setup.py, tox.ini
- Test discovery loaded a directory that did not exist
- All tests were executed twice due to duplication in test discovery
- Create Table called deprecated method `Domain.__bool__`
- Grep used an incorrect file path.
=> Fixes for migration to github actions

orangecontrib/prototypes/widgets/owunique.py, orangecontrib/prototypes/widgets/tests/test_owunique.py
- We decided to have a single list in which the user selects variables instead of two to drag between.
- I also added input and output summaries
- By default, and if nothing is selected, the widget uses all variables
=> OWUnique: Use a single list view instead of two

orangecontrib/prototypes/widgets/owinteractions.py
Include new icon in the widget
=> added icon to interactions widget

orangecontrib/prototypes/widgets/owinteractions.py, orangecontrib/prototypes/widgets/tests/test_owinteractions.py
- Split interaction and combined information gain into separate columns, and added ability to sort by either score or attribute.
- Added searchable tag to attribute selection combobox.
- Fix issue with formatting table only after computation is complete. (something that could also be changed in correlations widget)
=> [ENH] Interactions: Sorting

orangecontrib/prototypes/widgets/owchatgptconstructor.py
=> ChatGPT Constructor: Add widget

orangecontrib/prototypes/widgets/owchatgpt.py
- Save access key to system keyring service
- Add system content to the model
- Minor UI modifications
=> ChatGPT Summarize: Updates

orangecontrib/prototypes/widgets/owchatgptbase.py, orangecontrib/prototypes/widgets/owchatgptconstructor.py
The answers are not consistent.
- set temperature=0
- consider model type when using cached results
=> Chat GPT: Set temperature to 0, fix cache

orangecontrib/prototypes/widgets/owdfdisplay.py, orangecontrib/prototypes/widgets/oworaclesql.py
I saw some warnings every time I ran Orange and I silenced them.
=> [FIX] Data Frame Display: make it work again
