orangecontrib/prototypes/widgets/owlinearprojection.py
orangecontrib/prototypes/widgets/owpolynomialregression.py

Widgets in Orange 3 do not have arguments in __init__

Prototype extension: remove parent from __init__s

---

orangecontrib/prototypes/widgets/__init__.py

Hotfix for everyone that uses Orange before  https://github.com/biolab/orange3/pull/693 was merged.
Network will show in the add-ons dialog after the new version of prototype is installed.

Hotplug network add-on.

---

orangecontrib/prototypes/widgets/__init__.py

Pypi search is working again, so this hotfix is no longer needed.
This reverts commit e5c9280268a0858e5d2350b20dede30ba0255ff8.

Revert "Hotplug network add-on."

---

orangecontrib/prototypes/widgets/owsilhouetteplot.py

Set fixed height constraint on the text list to match the silhouette's
height.
When the cluster was small and it's (left) label taller then the
silhouette, the text list expanded/stretched to fill the available
vertical space, breaking the alignment between the silhouette bars and
list items.

owsilhouetteplot: Fix text annotations layout

---

orangecontrib/prototypes/widgets/owlookalike.py

When the reference image comes form the data set and we do not exclude it in the Neighbours widget we show `I am 1e+2% ...` and also the number is truncated in the left TableView. This commit changes the format to always show the full number with one decimal place and also widens TableView so that 100% matches are not truncated.

OWLookAlike: Show 100% match nicely

---

orangecontrib/prototypes/widgets/owneighbours.py
orangecontrib/prototypes/widgets/tests/test_owneighbours.py

The widget crashed with data with missing values. Now data is preprocessed (RemoveNaNColumns and Impute) before distances are computed.

OWNeighbours: Support missing values

---

orangecontrib/prototypes/widgets/owfreeviz.py
orangecontrib/prototypes/widgets/owlinearprojection.py
orangecontrib/prototypes/widgets/utils/axisitem.py
setup.py

* Fix Freeviz/Linear projection pyqtgraph 0.10 compatibility (`AttributeError: 'TextItem'
object has no attribute 'updateText'`)
* Update/set blocking state in Freeviz during optimization
* Add `Default` flag to "Data" input in Freeviz widget

[FIX] Fix pyqtgraph 0.10 compatibility

---

orangecontrib/prototypes/widgets/owreshape.py

Add a new widget for 'reshaping' a records table
i.e.
```
ID, V1, V2, V3
d,c,c,c
a,1,2,3
```
into
```
ID, Item, Value
d, d, c
a, V1, 1
a, V2, 2
a, V3, 3
```

Add a new widget for 'reshaping' a records table

---

orangecontrib/prototypes/widgets/owdatasets.py

I think the sizes are now more readable.
"Send data" is probably better than "Commit". Is it? Better ideas? @ajdapretnar?
I cannot not comment on this: the widget is written in @ales-erjavec's handwriting. It's great. None of us comes close to this.

Data sets: Right-align sizes, Change button text

---

orangecontrib/prototypes/widgets/owdatasets.py

1. If local cache has a file with a different version, widget lists that file as uncached. When the user selects and commits it, the file is updated (overwritten).
2. Data sets without a specified target have that column empty (i.e. also no icon).

Data Sets: check versions of local/remote file

---

orangecontrib/prototypes/widgets/owdatasets.py

Before the widget assumed that links have URL: link syntax. Uncommon, plus with rendering that displayed the entire URL. This has been changed so that assumed syntax is that of included HTML in the fields of the .info files.

[ENH] OWDataSets: all links are now in HTML

---

orangecontrib/prototypes/widgets/owdatasets.py

The widget would crash if tags field was None.

[FIX] Does not crash when tags are None

---

orangecontrib/prototypes/widgets/owdatasets.py

Crashed when any of the list fields to be included in HTML (essentially, the tag seealso) was None.

[FIX] Does not crash when list fields are None.

---

orangecontrib/prototypes/widgets/owfreeviz.py

Freeviz does not work since Orange 3.4.4.
Error caused by 
https://github.com/biolab/orange3/commit/7ec9a6d2753c4567d0ad0851aa294d3b6d58cc3a

[FIX] Freeviz: mdsplotutils -> Mdsplotutils

---

orangecontrib/prototypes/widgets/owneighbours.py

Fix broken compatibility with the latest core Orange distances.
Use the same approach as in Orange/widgets/owdistances.py.

[FIX] OWNeighbours: distance compatibility

---

orangecontrib/prototypes/widgets/owlda.py

LDA does not work anymore because **scikit-learn** has a different way to import **Linear Discriminant Analysis**.

[FIX] LDA: fix import

---

orangecontrib/prototypes/widgets/owimagegrid.py

**Image Grid** does not run anymore since https://github.com/biolab/orange3/pull/2807 was merged.
Now imports from Image Analytics add-on.

[FIX] Image Grid: import Image Viewer classes from add-on

---

orangecontrib/prototypes/widgets/owfeaturestatistics.py
orangecontrib/prototypes/widgets/tests/test_owfeaturestatistics.py
orangecontrib/prototypes/widgets/utils/histogram.py

Show basic statistics for every feature.
Features of note:
- Widget is usable with large datasets (means, vars and missing are computed on init, hisograms are computed and drawn as needed and cached) 
- Histograms keep their aspect ratio as the widget resizes (however, this ratio is ignored if the height is too small).
- Dropdown to enable coloring by any target variable, or disable coloring entirely.
- Filter textbox for variable names
- Sparse support
Todo:
- Sorting (currently uses slow `QSortFilterProxyModel`), special sorting by variable type, special sorting by first and second moment
- Implement report
- Attribute selection sends dataset with these attributes to output.
Current state (_housing_ and _GDS1615_, respectively):

[ENH] OWFeatureStatistics

---

orangecontrib/prototypes/widgets/icons/Grep.svg
orangecontrib/prototypes/widgets/owgrep.py
orangecontrib/prototypes/widgets/tests/test_owgrep.py
orangecontrib/prototypes/widgets/tests/test_owgrep_file.txt

A widget for getting the data from a text file, like a log.

OWGrep: Add widget

---

orangecontrib/prototypes/widgets/owlookalike.py

Lookalike widget was not adopted on new origin attribute for image paths which keeps the path to the directory.
Lookalike widget changed to consider booth path in the data table or path in the origin attribute.

Path fix in lookalike widget

---

orangecontrib/prototypes/widgets/owlineplot.py

Workaround to speed up the widget, but should be refactored, since many useless stuff is left from previous version.

OWLinePlot: Speed up widget set up for 'Mean' display

---

orangecontrib/prototypes/widgets/owfeaturestatistics.py
orangecontrib/prototypes/widgets/tests/test_owfeaturestatistics.py
orangecontrib/prototypes/widgets/utils/histogram.py

This turned very big, very fast. Sorry. I'll put other improvements in a separate PR, since this is already big as it is.
- Fixes #133 Sorting now works properly. I've also added variable type grouping, so that the dispersion in continuous variables is not mixed with modes of discrete variables, since it makes no sense to compare these. The sort order and column is stored as a ContextSetting
- Fixes #134 We don't show string variables anymore. After a bit of discussion in https://github.com/biolab/orange3/pull/2999, I realized treating time variables as ordinary continuous variables is perfectly reasonable. Center is the mean date, dispersion is the amount of time passed between the min and max date.
- Fixes #135 Outputs like in Rank. The selection is stored as a ContextSetting.
- …

Feature statistics improvements

---

orangecontrib/prototypes/widgets/owfeaturestatistics.py
orangecontrib/prototypes/widgets/tests/test_owfeaturestatistics.py
orangecontrib/prototypes/widgets/utils/histogram.py

Builds upon #137. This PR contains various fixes and improvements.
- 456c0ba widget would crash if given discrete variable where all the values would be the same
- f40a670 there was a coloring bug with continuous variables where all the values were the same. Discrete variables were colored incorrectly
- 7a8777a histograms would still show up if y was all nans and some sort of coloring was applied. Showing a histogram where the target var is all nans makes no sense, so hide them completely
- 6b79787 when inspecting a dataset with e.g. 40k variables, grouped sorting would result in a `MemoryError`. To fix this, the code is slightly uglier, but now sorting happens without issue and more efficiently.

[FIX] Feature statistics fixes (pt. 2)

---

orangecontrib/prototypes/widgets/contingency_table.py
orangecontrib/prototypes/widgets/owconfusionmatrix.py
orangecontrib/prototypes/widgets/owcontingency.py
orangecontrib/prototypes/widgets/tests/test_contingency_table.py
orangecontrib/prototypes/widgets/tests/test_owconfusionmatrix.py
orangecontrib/prototypes/widgets/tests/test_owcontingency.py

biolab/orange3#2966
Extracted the table in Confusion Matrix widget into a separate class and added a copy of Confusion Matrix widget which uses that class. Added this table and clustering scores to Contingency Table widget. Also added Selected Data and Data outputs which correspond to selected cells in the table (same as in Confusion Matrix).

[ENH] Show result in Contingency Table widget

---

setup.py

When the `orange3-prototypes` is installed, the `data` directory is missing. This makes the **Webcam Widget crash** when a photo is taken because the `haarcascade_frontalface_default.xml` file in the `data` directory is not found.
Add one line in the `setup.py` to include the `data` directory.

Include data directory in the installation

---

orangecontrib/prototypes/widgets/owcorrelations.py
orangecontrib/prototypes/widgets/tests/test_owcorrelations.py

When dataset is too big (i.e too many attributes or instances), it is impossible to calculate correlations for all attribute pairs. KMeans is used to suggest the most promising attribute pairs by selecting the pair within a cluster.

OWCorrelations: Use heuristic to get the most promising attribute pairs

---

orangecontrib/prototypes/widgets/owclock.py
orangecontrib/prototypes/widgets/owdbscan.py
orangecontrib/prototypes/widgets/owhub.py
orangecontrib/prototypes/widgets/owunique.py

Some widgets still used deprecated PyQt4.
Replace PyQt4 with AnyQt.

Change PyQt4 to AnyQt

---

orangecontrib/prototypes/widgets/owunique.py
orangecontrib/prototypes/widgets/tests/test_owunique.py

Fixes #188.
This in an ancient widget, but even in the days of old, settings worked not.
Sending callback via `QTimer` also probably didn't work properly - signals were not processed in the right order.
- The problem with settings is fixed by using a list of variables (instead tuple of lists, which `DomainContextHandler` does not understand). Settings are not migrated because they didn't work anyway.
- `set_data` now calls unconditional commit.
- Instead of callback from on drop event, commit is triggered by signals that indicate the model was changed. This makes a class derived from `QListView` unnecessary.
- Signals are migrated to new-style, models no longer wrap, widget preview is implemented as it's done now.
- Minor changes in GUI.
There are still no tests, but the refactored widget …

OWUnique: Fix settings, refactor and modernize

---

orangecontrib/prototypes/explanation/explainer.py
orangecontrib/prototypes/explanation/tests/test_explainer.py
setup.py

Script with functionalities to explain predictions
Before it works following PRs must be merged:
https://github.com/slundberg/shap/pull/1135 and Shap release
https://github.com/biolab/orange3/pull/4602 and Orange release

Script for explaining predictions

---

orangecontrib/prototypes/widgets/owexplainmodel.py
orangecontrib/prototypes/widgets/owexplainpred.py
orangecontrib/prototypes/widgets/tests/test_owexplainmodel.py
orangecontrib/prototypes/widgets/tests/test_owexplainpred.py

Implements #203
- change default zoom setting to something bigger
- (partially) Empty space above the stripe and below the stripe currently expand when zooming in. It would be better to always show just one tick (on the y-axis) above and one bellow the stripe.
- set tooltip at the model prediction number
- set tooltip at the base value number
- fix saved graph
- add target class to the report (explain model and explain prediction widgets)

[ENH] Explanation widgets updates

---

orangecontrib/prototypes/explanation/explainer.py
orangecontrib/prototypes/explanation/tests/test_explainer.py
orangecontrib/prototypes/widgets/tests/test_owexplainpred.py

It is possible that explained data have no class_var. In this case, the explanation failed since it was checking the class_var.
Whenever class_var is required use domain from the model.

[FIX] Explainer: fix case when data does not have domain

---

orangecontrib/prototypes/widgets/owcreatetable.py
orangecontrib/prototypes/widgets/tests/test_owcreatetable.py

Fixes https://github.com/biolab/orange3-prototypes/issues/222
Float values are recognized as continuous now.

CreateTable: fix float is continuous

---

orangecontrib/prototypes/widgets/owunique.py
orangecontrib/prototypes/widgets/tests/test_owunique.py

Widget silently crashes if domain is changed when the list view has a selection. Same as https://github.com/biolab/orange3/pull/5354
Remove selection before changing the model, not afterwards.
If you select something, change the data and change it back, the selection that you made on the first data is properly retrieved, but the list view is not properly updated and looks as if nothing was selected. This is a general issue, and is fixed in https://github.com/biolab/orange-widget-base/pull/147.

Unique: Fix crash on domain change; use auto summaries

---

orangecontrib/prototypes/widgets/owinteractions.py
orangecontrib/prototypes/widgets/tests/test_owinteractions.py

Adds widget for calculation of attribute interactions based on Orange's correlations widget. The returned results are consistent with the Interaction Graph widget from Orange2, however this is somewhat dependant on the discretization of the input data (this one handles continuous data via equal-frequency discretization). 
To simplify the code this widget inherits directly from owcorrelations, so the following Warning is raised:
`RuntimeWarning: subclassing of widget classes is deprecated and will be disabled in the future.
Extract code from OWCorrelations or explicitly open it by adding 'openclass=True' to class definition.
class OWInteractions(OWCorrelations):`
The solution is probably to construct a combined parent class for both owcorrelations and owinteractions.

[ENH] Interactions widget

---

MANIFEST.in
orangecontrib/prototypes/widgets/icons/Split.svg
orangecontrib/prototypes/widgets/owsplit.py
orangecontrib/prototypes/widgets/tests/orange-in-education.tab
orangecontrib/prototypes/widgets/tests/test_owsplit.py
setup.py

Survey and archaeological data often come with many categorical values separated by a delimiter. Orange had no option to create "one hot encoded" variables by splitting by a delimiter.
A widget that takes a delimiter and creates new variables by splitting on it.

OWSplit: new widget

---

orangecontrib/prototypes/widgets/owchatgpt.py
orangecontrib/prototypes/widgets/owchatgptbase.py
orangecontrib/prototypes/widgets/owchatgptconstructor.py

- ChatGPT Summarize and ChatGPT Constructor are too common so a base class is introduced
- Offload GPT query on a separate thread

[ENH] GPT: Offload work on separate thread

---

orangecontrib/prototypes/interactions.py
orangecontrib/prototypes/widgets/owinteractions.py
orangecontrib/prototypes/widgets/tests/test_owinteractions.py

Main thread is bogged down, causing all of Orange to run slowly.
Interaction calculation has been fixed to avoid using `np.unique(..., axis=0)`.

OWInteractions: fix calculation

---

orangecontrib/prototypes/widgets/owtexttocolumns.py

Old workflows with OWSplit didn't work.
Ensure name migration.

OWTextToColumns: add name migration

---

orangecontrib/prototypes/widgets/owtexttocolumns.py
orangecontrib/prototypes/widgets/tests/test_owtexttocolumns.py

Fixes #274.
The speed up in a74ea0605fcda4f0247fd1a066a14db1e06053d3 fails if some variable doesn't appear in any row. The reason is that the table of row indices that contain this value will be empty and empty arrays have a `dtype` `float`.
In #274, this happened because tables are converted in batches of 5000 rows, and there were batches that didn't contain some values.
In another scenario, this would happen in the domain conversion would be applied on a data different from the one on which it was created.
Add `dtype=int`.

Text to Columns: Fix dtype for empty arrays
